services:
  app_anilist:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.anilist
    environment:
      GRAPHQL_ENDPOINT: $APP_ANILIST_GRAPHQL_ENDPOINT
      HASURA_SERVICE_TOKEN_SECRET: $APP_ANILIST_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_ANILIST_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_ANILIST_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 4526:8080
